apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ajjj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ajjj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0073-app
  name: devfile-sample-ajjj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ajjj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ajjj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-ajjj@sha256:67049337683f80f2e77f71a89843ab07d3df71e4e12abe303b7ec4b3ae059c53
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
